### ISSUE TITLE
Deal with hanging branches

### ISSUE THREAD

**Issue by jdenholm** [Cambridge-ICCS/ml-training-material#37]
Can we deal with the various hanging branches, please? For example, the patch opened by Dom?

**Comment by jatkinson1000** [comment]
`main`, `colab`, and `gh-pages` are all required for workshop/website.
I have removed the patch as I closed the issue a while ago.
`JOSE` will exist until we merge the paper in.
Only remaining one is the additions by dominic in `[tweaks-for-ncas](https://github.com/Cambridge-ICCS/ml-training-material/tree/tweaks-for-ncas)` which contains some things that would be nice to implement.

**Comment by jatkinson1000** [comment]
Closing this as I have just merged @dorchard's `tweaks-for-ncas` branch.
